<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WBS_Assessment.Application\WBS_Assessment.Application.csproj" />
      <ProjectReference Include="..\WBS_Assessment.Infrastructure\WBS_Assessment.Infrastructure.csproj" />
    </ItemGroup>

</Project>
